# Generated by Django 5.2.6 on 2025-09-26 09:11

import core.model_utils
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_enable_extensions'),
        ('djstripe', '0002_2_10'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=250)),
                ('tags', models.TextField()),
                ('content', models.TextField()),
                ('icon', models.ImageField(blank=True, upload_to='blog_post_icons/')),
                ('image', models.ImageField(blank=True, upload_to='blog_post_images/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(default=core.model_utils.generate_random_key, max_length=30, unique=True)),
                ('experimental_flag', models.BooleanField(default=False)),
                ('state', models.CharField(choices=[('stranger', 'Stranger'), ('signed_up', 'Signed Up'), ('trial_started', 'Trial Started'), ('trial_ended', 'Trial Ended'), ('subscribed', 'Subscribed'), ('cancelled', 'Cancelled'), ('churned', 'Churned'), ('account_deleted', 'Account Deleted')], default='stranger', help_text="The current state of the user's profile", max_length=255)),
                ('customer', models.ForeignKey(blank=True, help_text="The user's Stripe Customer object, if it exists", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='djstripe.customer')),
                ('product', models.ForeignKey(blank=True, help_text="The user's Stripe Product object, if it exists", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='djstripe.product')),
                ('subscription', models.ForeignKey(blank=True, help_text="The user's Stripe Subscription object, if it exists", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='djstripe.subscription')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feedback', models.TextField(help_text='The feedback text')),
                ('page', models.CharField(help_text='The page where the feedback was submitted', max_length=255)),
                ('profile', models.ForeignKey(blank=True, help_text='The user who submitted the feedback', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='core.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileStateTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_state', models.CharField(choices=[('stranger', 'Stranger'), ('signed_up', 'Signed Up'), ('trial_started', 'Trial Started'), ('trial_ended', 'Trial Ended'), ('subscribed', 'Subscribed'), ('cancelled', 'Cancelled'), ('churned', 'Churned'), ('account_deleted', 'Account Deleted')], max_length=255)),
                ('to_state', models.CharField(choices=[('stranger', 'Stranger'), ('signed_up', 'Signed Up'), ('trial_started', 'Trial Started'), ('trial_ended', 'Trial Ended'), ('subscribed', 'Subscribed'), ('cancelled', 'Cancelled'), ('churned', 'Churned'), ('account_deleted', 'Account Deleted')], max_length=255)),
                ('backup_profile_id', models.IntegerField()),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_transitions', to='core.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
