# Generated by Django 5.2.6 on 2025-09-26 09:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='HackerNewsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment_id', models.BigIntegerField(unique=True)),
                ('comment_text', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('story_id', models.BigIntegerField()),
                ('story_title', models.CharField(max_length=500)),
                ('parent_id', models.BigIntegerField(blank=True, null=True)),
                ('comment_created_at', models.DateTimeField()),
                ('comment_created_at_i', models.BigIntegerField()),
                ('comment_updated_at', models.DateTimeField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('highlight_result', models.JSONField(blank=True, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hacker_news_comments', to='core.profile')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hacker_news_comments', to='core.source')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HackerNewsStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('story_id', models.BigIntegerField(unique=True)),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(blank=True, max_length=2000, null=True)),
                ('author', models.CharField(max_length=100)),
                ('points', models.IntegerField(default=0)),
                ('num_comments', models.IntegerField(default=0)),
                ('post_created_at', models.DateTimeField()),
                ('post_created_at_i', models.BigIntegerField()),
                ('post_updated_at', models.DateTimeField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('highlight_result', models.JSONField(blank=True, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hacker_news_stories', to='core.profile')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hacker_news_stories', to='core.source')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalWebsitePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.CharField(blank=True, max_length=20, null=True)),
                ('content', models.TextField(blank=True)),
                ('word_count', models.IntegerField(default=0)),
                ('meta_data', models.JSONField(blank=True, default=dict)),
                ('links', models.JSONField(blank=True, default=list)),
                ('images', models.JSONField(blank=True, default=list)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_website_pages', to='core.profile')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_website_pages', to='core.source')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
